version: '2'

services:
  next-on-drupal-dev:
    image: next-on-drupal
    build:
      context: ./config/docker/
    ports:
      - 3000:3000
    dns:
      - 8.8.8.8
    volumes:
      - $HOME/.ssh:/home/node/.ssh
      - $HOME/.gitconfig:/home/node/.gitconfig
      - $HOME/.now:/home/node/.now
      - $PWD:/home/node/app
      - $PWD/config/docker/.bash_history:/home/node/.bash_history
